# Generated by Django 5.1.1 on 2024-10-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_rename_comment_postreview_content_postreview_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreview',
            old_name='content',
            new_name='comment',
        ),
    ]
