# Generated by Django 5.1.1 on 2024-10-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_remove_post_tags_name_post_author_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreview',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
