# Generated by Django 5.1.1 on 2024-10-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_postreview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
